export const surveyQuestions = [
    'What’s your current project, and what inspired it?',
    // 'Looking for some help? Share what you need and why.',
    // 'What’s your unique skill, and how do you use it?',
    // 'In what ways can you support others here?',
    // 'What’s your ultimate goal? What are you aiming to achieve?',
    // 'Who’s on your top list to meet and why?',
    // 'What brought you to this event? What are you excited about?',
    // 'Your favorite hangout spot – where is it, and why do you love it?',
    // 'Time for a humble brag – what’s something great about you?',
    // 'What’s your current passion outside of work?',
    // 'If you could meet anyone, alive or passed, who would it be and why?',
    // 'Imagine a world where AI does everything. What would you do?',
    // 'Where does your motivation come from?',
    // 'Tell us about your best friend – how did you meet, and what makes your friendship special?',
    // 'What’s important to you when meeting new people?',
    // 'We’d love to know more about you. Share your story!',
];
